config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :participants
   root 'welcome#index'

end

app/models/participant.rb
class Participant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
def new
  end
  def create
  @article = Article.new(params[:article])
  @article.save
  redirect_to @article
  render plain: params[:participant].inspect
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/participants/new.html.erb
<h1>New participant</h1>
<%= form_for :participant, url: participant_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>welcome aboard</h1>